# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingholiday', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostId', models.CharField(blank=True, max_length=200, null=True)),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('hostarea', models.CharField(blank=True, choices=[('Taipei', 'Taipei'), ('Keelung', 'Keelung'), ('Taoyuan', 'Taoyuan'), ('Hsinchu', 'Hsinchu'), ('Miaoli', 'Miaoli'), ('Taichung', 'Taichung'), ('Nantou', 'Nantou'), ('Changhua', 'Changhua'), ('Yunlin', 'Yunlin'), ('Chiayi', 'Chiayi'), ('Tainan', 'Tainan'), ('Kaohsiung', 'Kaohsiung'), ('Pingtung', 'Pingtung'), ('Taitung', 'Taitung'), ('Hualien ', 'Hualien '), ('Yilan', 'Yilan'), ('Liuqiu', 'Liuqiu'), ('Ludao', 'Ludao'), ('Lanyu', 'Lanyu'), ('Penghu', 'Penghu'), ('Kinmen', 'Kinmen'), ('Lienchiang', 'Lienchiang')], default='Taipei', max_length=50, null=True)),
                ('hostaddress', models.CharField(max_length=50)),
                ('hostemail', models.EmailField(max_length=254)),
                ('hostphone', models.CharField(max_length=50)),
                ('hostintro', models.CharField(max_length=500)),
                ('hostneed', models.CharField(max_length=200)),
                ('hostbrief', models.CharField(max_length=200)),
                ('hostimage1', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('hostimage2', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('hostimage3', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('hostimage4', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
    ]
