# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingholiday', '0003_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostarea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
