# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingholiday', '0005_host_hostpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostId', models.CharField(blank=True, max_length=200, null=True)),
                ('applyId', models.CharField(blank=True, max_length=200, null=True)),
                ('applyMonth', models.CharField(blank=True, max_length=200, null=True)),
                ('applyName', models.CharField(blank=True, max_length=200, null=True)),
                ('applyIntro', models.CharField(blank=True, max_length=500, null=True)),
                ('applyHostName', models.CharField(blank=True, max_length=200, null=True)),
                ('applyHostIntro', models.CharField(blank=True, max_length=500, null=True)),
                ('applyPicture', models.URLField(blank=True, null=True)),
                ('hostPicture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
