# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingholiday', '0006_applymanage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostId', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmId', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmMonth', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmName', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmIntro', models.CharField(blank=True, max_length=500, null=True)),
                ('confirmPicture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmUserManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostId', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmId', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmMonth', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmHostName', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmHostIntro', models.CharField(blank=True, max_length=500, null=True)),
                ('confirmPicture', models.URLField(blank=True, null=True)),
                ('hostPicture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostId', models.CharField(blank=True, max_length=200, null=True)),
                ('commentId', models.CharField(blank=True, max_length=200, null=True)),
                ('commentName', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('commentPicture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=200, null=True)),
                ('commentId', models.CharField(blank=True, max_length=200, null=True)),
                ('commentName', models.CharField(blank=True, max_length=200, null=True)),
                ('commentHostName', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('commentPicture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
