# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingholiday', '0007_confirmmanage_confirmusermanage_hostcomment_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='commentarea',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
