# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingholiday', '0009_host_hostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostcomment',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
    ]
