# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workingholiday', '0010_auto_20161215_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostcomment',
            field=models.IntegerField(default=0),
        ),
    ]
